Fix: ares flatpak not picking up shaders and database folders
flathub/dev.ares.ares pull request #29
Opened 2023-07-25 00:03 UTC by rawdatafeel

Closes: https://github.com/flathub/dev.ares.ares/issues/18

Depends on: https://github.com/flathub/dev.ares.ares/pull/28

Some of the patch is ported over from: https://aur.archlinux.org/cgit/aur.git/tree/ares-paths.patch?h=ares-emu

Tested and works ok.

2023-08-02 14:55 UTC, ghisvail commented
LGTM, though it would be nice to open an issue upstream (and warn them about the patch), so that both Arch and Flatpak builds can track potential progress on that front.

AFAIU, a solution would be to make the build system take the prefix argument into account when computing the shared data path, instead of hardcoding it to `/usr/share`.

2023-08-04 09:41 UTC, Mastergatto requested changes

2023-08-05 20:01 UTC, Mastergatto commented
Hi, https://github.com/ares-emulator/ares/pull/1178 has just been merged, thus eliminating the need for this patch, except for the prefix thing. I'm sorry, but I couldn't come with a good solution at the moment.

2023-08-05 21:29 UTC, ghisvail commented
> I've opened an issue on the ares repo suggesting to not hard-code the /usr/share line in path.cpp, but in the meantime, this patch will do the trick.

https://github.com/ares-emulator/ares/issues/1179

> It doesn't break anything in my testing, so it seems okay to merge as is (but won't actually fix the shaders/database folders until v134).

Sounds good to me. Thanks to both of you (@Mastergatto and @rawdatafeel) for providing as much as we possibly could upstream and making them aware of our needs. The Arch people never fail to deliver 👍

2023-08-05 21:29 UTC, merged